### PR TITLE
Port, update, progress

### PR DESCRIPTION
**Pull request by falseresync**

### CODE REVIEW

**Comment by LemmaEOF** [comment]
I think this should definitely do either *only* UC or *only* LBA; using both leads to a *lot* of confusion.

**Comment by falseresync** [comment]
I like UC more, so I will switch to it as soon as FluidVolume API is ready

**Comment by LemmaEOF** [comment]
For VivaTech's purposes, it's pretty much fully ready. What's not ready for it to be PR'd into fabric is fluid properties, which is per-instance arbitrary data storage (abstracted from NBT).

**Comment by falseresync** [comment]
Yeah, I am looking at it, seems done enough indeed

**Comment by falseresync** [comment]
LBA is still required tho for current energy system, so it will go a bit later

**Comment by LemmaEOF** [comment]
UC folded Cotton Energy in though

**Comment by falseresync** [comment]
Yeah, I haven't bothered remapping the thing yet :P

**Pull request closed without merging**
